### ISSUE TITLE
[bug] AO P/P: a failed Pong stops all processing

### ISSUE THREAD

**Issue by pointops** [bitfinexcom/bfx-hf-algo#182]
Ping-Ping AO fails to keep going after first PONG gets filled

#### Steps to reproduce
- setup P/P with multiple orders, e.g. Ping/Pong | -0.0002:-0.0002 @ [48360..48550] -> -10
- watch out for the first PONG to be filled

#### Problem
- PONG does not generate new PING
- if price move back towards virgin PINGs from the original order, they no longer will generate PONGS
- if any other P/P a.o. exist, it will not execute anymore even if never filled

#### Logs: from api-server

> 021-08-22T18:25:41.686Z bfx:hf:algo:ao-host:ws2:process-message process order:close [0/0.00021 @ 48329 EXECUTED @ 48329.0(0.00021)]
2021-08-22T18:25:41.686Z bfx:hf:algo:ao-host triggering order event orders:order_close for AO bfx-ping_pong [gid 1629656609334, o cid 1629656609343, 0.00021 @ 48329 EXECUTED @ 48329.0(0.00021)]
2021-08-22T18:25:41.686Z bfx:hf:algo:ao-host triggering order event orders:order_fill for AO bfx-ping_pong [gid 1629656609334, o cid 1629656609343, 0.00021 @ 48329 EXECUTED @ 48329.0(0.00021)]
2021-08-22T18:25:41.686Z bfx:hf:algo:ao-host triggering orders:order_fill for AO bfx-ping_pong [gid 1629656609334]
2021-08-22T18:25:41.686Z bfx:hf:algo:bfx-ping_pong:1629656609334 submitting pong order 48339 for ping 48329
2021-08-22T18:25:41.686Z bfx:hf:algo:bfx-ping_pong:1629656609334 emit exec:order:submit:all [at onOrdersOrderFill (/home/user/Apps/bfx-desktop/resources/app/node_modules/bfx-hf-algo/lib/ping_pong/events/orders_order_fill.js:102:9)]
2021-08-22T18:25:41.686Z bfx:hf:algo:bfx-ping_pong:1629656609334 submitting order LIMIT -0.00021 @ 48339 [gid 1629656741686] 1629656609334
2021-08-22T18:25:41.686Z bfx:hf:algo:bfx-ping_pong:1629656609334 submitOrder (attempt 1): (cid: 1629656741686) LIMIT order on BTC/USD for -0.00021000 @ 48339 [at /home/user/Apps/bfx-desktop/resources/app/node_modules/bfx-hf-algo/lib/host/events/submit_all_orders.js:71:11]
2021-08-22T18:25:41.722Z bfx:hf:algo:bfx-ping_pong:1629656609334 order successfully submitted: LIMIT -0.00021 @ 48339 ACTIVE
2021-08-22T18:25:41.722Z bfx:hf:algo:bfx-ping_pong:1629656609334 updateState [at onOrdersOrderFill (/home/user/Apps/bfx-desktop/resources/app/node_modules/bfx-hf-algo/lib/ping_pong/events/orders_order_fill.js:103:9)]
2021-08-22T18:25:41.722Z bfx:hf:algo:bfx-ping_pong:1629656609334 emit state:update [at updateState (/home/user/Apps/bfx-desktop/resources/app/node_modules/bfx-hf-algo/lib/host/gen_helpers.js:424:13)]
2021-08-22T18:25:41.724Z bfx:hf:algo:ao-host:ws2:bind-bus enqueue order:new
2021-08-22T18:25:41.724Z bfx:hf:algo:ao-host:ws2:process-message process order:new [-0.00021/-0.00021 @ 48339 ACTIVE]
2021-08-22T18:25:41.724Z bfx:hf:algo:ao-host triggering order event orders:order_new for AO bfx-ping_pong [gid 1629656609334, o cid 1629656741686, -0.00021 @ 48339 ACTIVE]
2021-08-22T18:26:35.714Z bfx:hf:algo:ao-host:ws2:bind-bus enqueue order:close
2021-08-22T18:26:35.714Z bfx:hf:algo:ao-host:ws2:process-message process order:close [0/-0.00021 @ 48339 EXECUTED @ 48339.0(-0.00021)]
2021-08-22T18:26:35.714Z bfx:hf:algo:ao-host triggering order event orders:order_close for AO bfx-ping_pong [gid 1629656609334, o cid 1629656741686, -0.00021 @ 48339 EXECUTED @ 48339.0(-0.00021)]
2021-08-22T18:26:35.714Z bfx:hf:algo:ao-host triggering order event orders:order_fill for AO bfx-ping_pong [gid 1629656609334, o cid 1629656741686, -0.00021 @ 48339 EXECUTED @ 48339.0(-0.00021)]
2021-08-22T18:26:35.714Z bfx:hf:algo:ao-host triggering orders:order_fill for AO bfx-ping_pong [gid 1629656609334]
**2021-08-22T18:26:35.715Z bfx:hf:algo:ao-host:ws2:bind-bus error processing: TypeError: Cannot read property '1' of undefined**
    at extract (/home/user/Apps/bfx-desktop/resources/app/node_modules/bfx-hf-algo/lib/ping_pong/util/ping_pong_table.js:14:29)
    at onOrdersOrderFill (/home/user/Apps/bfx-desktop/resources/app/node_modules/bfx-hf-algo/lib/ping_pong/events/orders_order_fill.js:47:42)
    at AOHost.triggerAOEvent (/home/user/Apps/bfx-desktop/resources/app/node_modules/bfx-hf-algo/lib/ao_host.js:824:11)
    at /home/user/Apps/bfx-desktop/resources/app/node_modules/bfx-hf-algo/lib/ao_host.js:766:20
    at Array.map (<anonymous>)
    at AOHost.triggerOrderEvent (/home/user/Apps/bfx-desktop/resources/app/node_modules/bfx-hf-algo/lib/ao_host.js:732:33)
    at module.exports (/home/user/Apps/bfx-desktop/resources/app/node_modules/bfx-hf-algo/lib/host/ws2/process_message.js:111:15)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async processMessages (/home/user/Apps/bfx-desktop/resources/app/node_modules/bfx-hf-algo/lib/host/ws2/bind_bus.js:30:7)**
2021-08-22T18:26:44.657Z bfx:hf:algo:ao-host:ws2:bind-bus enqueue order:close

#### Remarks
- may even track back to v 3.14
- did not test on single ping/pong yet, only multiple, "sliced" ping-pong
- it is not a simple mis-behaviour of the ENDLESS option. Instead, the fill of PONG stops all other processing

orphaned atomics: 
(screenshot 30 minutes after the logfile above) 
![obrazek](https://user-images.githubusercontent.com/80652610/130366656-f58597b5-ba09-49e3-8822-6bcad90222c3.png)
no PONGS from anything issued after the event logged above

original AO recipes:
![obrazek](https://user-images.githubusercontent.com/80652610/130366722-94a23d1f-1878-4862-bfc1-1bbd37d96e67.png)

**Comment by pointops** [comment]
**UPDATE**

Tested the zipped 3.15.0 WIN bfx-hf-ui from reposititory here on Github.

Same effect, crashes already at the very first PONG creation (unlike what's reported above).

https://github.com/bitfinexcom/bfx-hf-ui/issues/576

**Comment by pointops** [comment]
Update: Now confirmed on 3.17.0

also, once the first error is thrown for one ping-pong AO, the another present one (yet untouched) gets affected too. Any fills that may come don't create pongs, not even the first one of the other AO.

**Comment by tarcisiozf** [comment]
fix incoming: https://github.com/bitfinexcom/bfx-hf-algo/pull/183
